# Generated by Django 3.2.3 on 2021-06-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directMessages', '0002_auto_20210602_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
